### ISSUE TITLE
AUTH0_DB_NAME in the .env file should be optional and default to empty string

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#207]
AUTH0_DB_NAME could be optional, so that default AUTH0 db will be used.
Currently it is impossible to start without this variable:
```
(dprtest)u1@pc1:/home/z/pproj/dprapitest> python dpr.py 
Traceback (most recent call last):
  File "dpr.py", line 9, in <module>
    application = create_app()
  File "/home/z/pproj/dprapitest/app/__init__.py", line 42, in create_app
    app.config.from_object(get_config_class_name())
  File "/home/z/pproj/dprapitest/app/__init__.py", line 35, in get_config_class_name
    getattr(config_class, 'check_required_config')()
  File "/home/z/pproj/dprapitest/app/config.py", line 56, in check_required_config
    raise Exception("value of %s can not be None" % conf)
Exception: value of AUTH0_DB_NAME can not be None
```

**Comment by rufuspollock** [comment]
+1

**Comment by rufuspollock** [comment]
INVALID. Removal of auth0 in #268 obsoletes this.
