### ISSUE TITLE
POST /api/auth/token ValueError: View function did not return a response

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#27]
When some invalid secret is submitted to POST /api/auth/token, the server throws error and returns empty 500 response. It should return authorization error instead.
```
127.0.0.1 - - [01/Nov/2016 23:59:11] "POST /api/auth/token HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/u1/.virtualenvs/dpr/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/u1/.virtualenvs/dpr/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/u1/.virtualenvs/dpr/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/u1/.virtualenvs/dpr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/u1/.virtualenvs/dpr/lib/python2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/u1/.virtualenvs/dpr/lib/python2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

**Comment by subhankarb** [comment]
Addressed by https://github.com/frictionlessdata/dpr-api/pull/28
